"""
Agent 4: The Archivist — Living Context Maintainer
Produces CODEBASE.md, onboarding_brief.md, and cartography_trace.jsonl.
"""
from __future__ import annotations
import json
import os
from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime, timezone

import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from src.models import AnalysisTrace, CartographyResult
from src.graph.knowledge_graph import KnowledgeGraph


class Archivist:
    """Produces all living artifacts from analysis results."""

    def __init__(self, kg: KnowledgeGraph, output_dir: str):
        self.kg = kg
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        self.traces: List[AnalysisTrace] = []

    def _trace(self, action: str, target: str, result: str):
        self.traces.append(AnalysisTrace(
            timestamp=datetime.now(timezone.utc).isoformat(),
            agent="archivist",
            action=action,
            target=target,
            result_summary=result,
            evidence_source="static_analysis",
        ))

    def run(self, result: CartographyResult, all_traces: List[AnalysisTrace]) -> None:
        print(f"  [Archivist] Writing artifacts to {self.output_dir}...")

        self.generate_codebase_md(result)
        self.generate_onboarding_brief(result)
        self.kg.save_module_graph(os.path.join(self.output_dir, "module_graph.json"))
        self.kg.save_lineage_graph(os.path.join(self.output_dir, "lineage_graph.json"))
        self.write_trace_log(all_traces + self.traces)

        print(f"  [Archivist] All artifacts written.")

    def generate_codebase_md(self, result: CartographyResult) -> str:
        """Generate CODEBASE.md — the living context file for AI agent injection."""
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# CODEBASE.md — {result.repo_name}",
            f"*Auto-generated by Brownfield Cartographer on {ts}*",
            f"*Inject this file as system prompt context for AI coding agents.*",
            "",
            "---",
            "",
            "## Architecture Overview",
            "",
        ]

        # Architecture narrative
        module_count = len(result.module_nodes)
        dataset_count = len(result.dataset_nodes)
        lang_counts: Dict[str, int] = {}
        for m in result.module_nodes.values():
            lang_counts[m.language] = lang_counts.get(m.language, 0) + 1
        lang_str = ', '.join(f"{v} {k}" for k, v in sorted(lang_counts.items(), key=lambda x: -x[1]))

        lines.append(f"**Repo:** `{result.repo_name}` | **Analyzed:** {ts}")
        lines.append(f"**Scale:** {module_count} modules ({lang_str}) | {dataset_count} datasets/tables")
        lines.append("")
        lines.append("This is a production data engineering codebase. The system ingests data from external")
        lines.append("sources, transforms it through a series of pipeline stages, and produces output datasets.")
        lines.append("")

        # Domain clusters
        if result.domain_clusters:
            lines.append("## Domain Architecture Map")
            lines.append("")
            for domain, paths in sorted(result.domain_clusters.items()):
                if paths:
                    example_files = [Path(p).name for p in paths[:3]]
                    lines.append(f"**{domain.upper()}** ({len(paths)} modules) — e.g. {', '.join(example_files)}")
            lines.append("")

        # Critical path (top 5 by PageRank)
        lines.append("## Critical Path (Top Modules by Import Frequency)")
        lines.append("")
        top_modules = sorted(result.pagerank_scores.items(), key=lambda x: x[1], reverse=True)[:5]
        for i, (path, score) in enumerate(top_modules, 1):
            module = result.module_nodes.get(path)
            purpose = module.purpose_statement if module else ""
            lines.append(f"{i}. **`{Path(path).name}`** (PageRank: {score:.4f})")
            if purpose:
                lines.append(f"   - {purpose[:150]}")
        lines.append("")

        # Data sources and sinks
        sources = self.kg.find_sources()
        sinks = self.kg.find_sinks()
        lines.append("## Data Sources & Sinks")
        lines.append("")
        lines.append(f"**Entry Points (Sources):** {', '.join(sources[:8]) if sources else 'None detected'}")
        lines.append(f"**Output Datasets (Sinks):** {', '.join(sinks[:8]) if sinks else 'None detected'}")
        lines.append("")

        # Known debt
        lines.append("## Known Technical Debt")
        lines.append("")
        if result.circular_dependencies:
            lines.append(f"**Circular Dependencies ({len(result.circular_dependencies)} groups):**")
            for cycle in result.circular_dependencies[:3]:
                lines.append(f"  - {' → '.join(Path(p).name for p in cycle)}")
        drift_modules = [p for p, m in result.module_nodes.items() if m.doc_drift_flag]
        if drift_modules:
            lines.append(f"**Documentation Drift ({len(drift_modules)} modules):** Docstrings contradict implementation.")
            for p in drift_modules[:5]:
                lines.append(f"  - `{Path(p).name}`")
        if not result.circular_dependencies and not drift_modules:
            lines.append("No major debt signals detected.")
        lines.append("")

        # High velocity files
        lines.append("## High-Velocity Files (Active Pain Points)")
        lines.append("")
        if result.high_velocity_files:
            for path, count in result.high_velocity_files[:10]:
                lines.append(f"- `{Path(path).name}`: {count} commits in 30d")
        else:
            lines.append("Git velocity data unavailable (not a git repo or no recent commits).")
        lines.append("")

        # Module Purpose Index
        lines.append("## Module Purpose Index")
        lines.append("")
        for path, module in sorted(result.module_nodes.items(), key=lambda x: x[0]):
            if module.purpose_statement and not module.purpose_statement.startswith('['):
                lines.append(f"**`{Path(path).name}`** (`{path}`)")
                lines.append(f"  > {module.purpose_statement[:200]}")
        lines.append("")

        # Day-One Answers
        if result.day_one_answers:
            lines.append("## FDE Day-One Quick Reference")
            lines.append("")
            q_labels = {
                "q1_primary_ingestion": "Q1: Primary Ingestion Path",
                "q2_critical_outputs": "Q2: Critical Output Datasets",
                "q3_blast_radius": "Q3: Blast Radius of Critical Module",
                "q4_business_logic": "Q4: Business Logic Location",
                "q5_change_velocity": "Q5: Change Velocity (Last 90d)",
            }
            for key, label in q_labels.items():
                if key in result.day_one_answers:
                    lines.append(f"**{label}:**")
                    lines.append(f"{result.day_one_answers[key]}")
                    lines.append("")

        content = '\n'.join(lines)
        out_path = os.path.join(self.output_dir, "CODEBASE.md")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        self._trace("write_codebase_md", out_path, f"Written {len(content)} chars")
        return content

    def generate_onboarding_brief(self, result: CartographyResult) -> str:
        """Generate onboarding_brief.md — the FDE Day-One Brief."""
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# FDE Day-One Onboarding Brief",
            f"## Codebase: {result.repo_name}",
            f"*Generated: {ts} by Brownfield Cartographer*",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"This brief covers `{result.repo_name}`, a codebase with {len(result.module_nodes)} modules",
            f"and {len(result.dataset_nodes)} tracked datasets.",
            "",
            "---",
            "",
            "## The Five FDE Day-One Questions",
            "",
        ]

        q_labels = {
            "q1_primary_ingestion": ("1. What is the primary data ingestion path?", "🔵"),
            "q2_critical_outputs": ("2. What are the 3-5 most critical output datasets?", "🟢"),
            "q3_blast_radius": ("3. What is the blast radius if the critical module fails?", "🔴"),
            "q4_business_logic": ("4. Where is business logic concentrated vs. distributed?", "🟡"),
            "q5_change_velocity": ("5. What has changed most frequently (git velocity)?", "⚡"),
        }

        for key, (question, icon) in q_labels.items():
            lines.append(f"### {icon} {question}")
            lines.append("")
            answer = result.day_one_answers.get(key, "Analysis incomplete — run Semanticist agent.")
            lines.append(answer)
            lines.append("")

        # Architecture snapshot
        lines.extend([
            "---",
            "",
            "## Architecture Snapshot",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total Modules | {len(result.module_nodes)} |",
            f"| Total Datasets | {len(result.dataset_nodes)} |",
            f"| Transformations | {len(result.transformation_nodes)} |",
            f"| Circular Deps | {len(result.circular_dependencies)} |",
            f"| Doc Drift Flags | {sum(1 for m in result.module_nodes.values() if m.doc_drift_flag)} |",
            "",
        ])

        # Top modules
        if result.pagerank_scores:
            top = sorted(result.pagerank_scores.items(), key=lambda x: x[1], reverse=True)[:5]
            lines.append("## Top 5 Architectural Hubs (by PageRank)")
            lines.append("")
            for rank, (path, score) in enumerate(top, 1):
                m = result.module_nodes.get(path)
                domain = m.domain_cluster if m else ""
                lines.append(f"{rank}. `{path}` — PageRank: {score:.5f} | Domain: {domain}")
            lines.append("")

        # Data lineage summary
        sources = self.kg.find_sources()
        sinks = self.kg.find_sinks()
        lines.extend([
            "## Data Lineage Summary",
            "",
            f"**Source Tables / Files:** {', '.join(sources[:8]) or 'None detected'}",
            f"**Output Tables / Files:** {', '.join(sinks[:8]) or 'None detected'}",
            "",
            "---",
            "",
            "*This brief was auto-generated. Verify critical path answers against live codebase.*",
        ])

        content = '\n'.join(lines)
        out_path = os.path.join(self.output_dir, "onboarding_brief.md")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        self._trace("write_onboarding_brief", out_path, f"Written {len(content)} chars")
        return content

    def write_trace_log(self, all_traces: List[AnalysisTrace]) -> None:
        out_path = os.path.join(self.output_dir, "cartography_trace.jsonl")
        with open(out_path, "w", encoding="utf-8") as f:
            for trace in all_traces:
                f.write(trace.to_jsonl() + '\n')
        self._trace("write_trace_log", out_path, f"Written {len(all_traces)} trace entries")